module.exports = {
    apps: [
        {
            name: "stat_dcs004",
            script: "/bin/bash", // 使用 Bash 作为解释器
            args: '-c "taskset -c 34 node stat.js --account dcs004"', // 传递给 bash 的完整命令
            out_file: "logs/stat-dcs004-out.log",
            error_file: "logs/stat-dcs004-error.log",
        },
        {
            name: "stat_dcs005",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs005"',
            out_file: "logs/stat-dcs005-out.log",
            error_file: "logs/stat-dcs005-error.log",
        },
        {
            name: "stat_dcs006",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs006"',
            out_file: "logs/stat-dcs006-out.log",
            error_file: "logs/stat-dcs006-error.log",
        },
        {
            name: "stat_dcs008",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs008"',
            out_file: "logs/stat-dcs008-out.log",
            error_file: "logs/stat-dcs008-error.log",
        },
        {
            name: "stat_dcs009",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs009"',
            out_file: "logs/stat-dcs009-out.log",
            error_file: "logs/stat-dcs009-error.log",
        },
        {
            name: "stat_dcs010",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs010"',
            out_file: "logs/stat-dcs010-out.log",
            error_file: "logs/stat-dcs010-error.log",
        },
        {
            name: "stat_dcs011",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs011"',
            out_file: "logs/stat-dcs011-out.log",
            error_file: "logs/stat-dcs011-error.log",
        },
        {
            name: "stat_sma001",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma001"',
            out_file: "logs/stat-sma001-out.log",
            error_file: "logs/stat-sma001-error.log",
        },
        {
            name: "stat_sma002",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma002"',
            out_file: "logs/stat-sma002-out.log",
            error_file: "logs/stat-sma002-error.log",
        },
        {
            name: "stat_sma003",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma003"',
            out_file: "logs/stat-sma003-out.log",
            error_file: "logs/stat-sma003-error.log",
        },
        {
            name: "stat_sma004",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma004"',
            out_file: "logs/stat-sma004-out.log",
            error_file: "logs/stat-sma004-error.log",
        },
        {
            name: "stat_dcs012",
            script: "/bin/bash",
            args: '-c "taskset -c 0 node stat.js --account dcs012"',
            out_file: "logs/stat-dcs012-out.log",
            error_file: "logs/stat-dcs012-error.log",
        },
        {
            name: "stat_dcs013",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs013"',
            out_file: "logs/stat-dcs013-out.log",
            error_file: "logs/stat-dcs013-error.log",
        },
        {
            name: "stat_dcs014",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs014"',
            out_file: "logs/stat-dcs014-out.log",
            error_file: "logs/stat-dcs014-error.log",
        },
        {
            name: "stat_dcs015",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs015"',
            out_file: "logs/stat-dcs015-out.log",
            error_file: "logs/stat-dcs015-error.log",
        },
        {
            name: "stat_dcs061",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account dcs061"',
            out_file: "logs/stat-dcs061-out.log",
            error_file: "logs/stat-dcs061-error.log",
        },
        {
            name: "stat_dcs062",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs062"',
            out_file: "logs/stat-dcs062-out.log",
            error_file: "logs/stat-dcs062-error.log",
        },
        {
            name: "stat_dcs063",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs063"',
            out_file: "logs/stat-dcs063-out.log",
            error_file: "logs/stat-dcs063-error.log",
        },
        {
            name: "stat_dcs064",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs064"',
            out_file: "logs/stat-dcs064-out.log",
            error_file: "logs/stat-dcs064-error.log",
        },
        {
            name: "stat_dcs065",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs065"',
            out_file: "logs/stat-dcs065-out.log",
            error_file: "logs/stat-dcs065-error.log",
        },
        {
            name: "stat_dcs066",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs066"',
            out_file: "logs/stat-dcs066-out.log",
            error_file: "logs/stat-dcs066-error.log",
        },
        {
            name: "stat_dcs067",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs067"',
            out_file: "logs/stat-dcs067-out.log",
            error_file: "logs/stat-dcs067-error.log",
        },
        {
            name: "stat_dcs068",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs068"',
            out_file: "logs/stat-dcs068-out.log",
            error_file: "logs/stat-dcs068-error.log",
        },
        {
            name: "stat_dcs069",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs069"',
            out_file: "logs/stat-dcs069-out.log",
            error_file: "logs/stat-dcs069-error.log",
        },
        {
            name: "stat_dcs070",
            script: "/bin/bash",
            args: '-c "taskset -c 31 node highLeverStat.js --account dcs070"',
            out_file: "logs/stat-dcs070-out.log",
            error_file: "logs/stat-dcs070-error.log",
        },
        {
            name: "stat_sma009",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma009"',
            out_file: "logs/stat-sma009-out.log",
            error_file: "logs/stat-sma009-error.log",
        },
        {
            name: "stat_sma010",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma010"',
            out_file: "logs/stat-sma010-out.log",
            error_file: "logs/stat-sma010-error.log",
        },
        {
            name: "stat_sma011",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma011"',
            out_file: "logs/stat-sma011-out.log",
            error_file: "logs/stat-sma011-error.log",
        },
        {
            name: "stat_sma012",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma012"',
            out_file: "logs/stat-sma012-out.log",
            error_file: "logs/stat-sma012-error.log",
        },
        {
            name: "stat_sma013",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account sma013"',
            out_file: "logs/stat-sma013-out.log",
            error_file: "logs/stat-sma013-error.log",
        },
        {
            name: "stat_daphne1",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account daphne1"',
            out_file: "logs/stat-daphne1-out.log",
            error_file: "logs/stat-daphne1-error.log",
        },
        {
            name: "stat_daphne2",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account daphne2"',
            out_file: "logs/stat-daphne2-out.log",
            error_file: "logs/stat-daphne2-error.log",
        },
        {
            name: "stat_daphne3",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account daphne3"',
            out_file: "logs/stat-daphne3-out.log",
            error_file: "logs/stat-daphne3-error.log",
        },
        {
            name: "stat_daphne4",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node stat.js --account daphne4"',
            out_file: "logs/stat-daphne4-out.log",
            error_file: "logs/stat-daphne4-error.log",
        },
        {
            name: "monit_zmq",
            script: "/bin/bash",
            args: '-c "taskset -c 34 node monit-zmq.js"',
            out_file: "logs/monit-zmq-out.log",
            error_file: "logs/monit-zmq-error.log",
        },
    ],
};
