module.exports = {
    apps: [
        {
            name: "hedge",
            script: "hedge.js",
            args: "",
            out_file: "logs/hedge-out.log",
            error_file: "logs/hedge-error.log",
        },
        {
            name: "stat_dcs009",
            script: "stat.js",
            args: "--account dcs009",
            out_file: "logs/stat-dcs009-out.log",
            error_file: "logs/stat-dcs009-out.log",
        },
        {
            name: "stat_dcs010",
            script: "stat.js",
            args: "--account dcs010",
            out_file: "logs/stat-dcs010-out.log",
            error_file: "logs/stat-dcs010-out.log",
        },
        {
            name: "stat_dcs011",
            script: "stat.js",
            args: "--account dcs011",
            out_file: "logs/stat-dcs011-out.log",
            error_file: "logs/stat-dcs011-out.log",
        },
        {
            name: "stat_sma001",
            script: "stat.js",
            args: "--account sma001",
            out_file: "logs/stat-sma001-out.log",
            error_file: "logs/stat-sma001-out.log",
        },
        {
            name: "stat_sma002",
            script: "stat.js",
            args: "--account sma002",
            out_file: "logs/stat-sma002-out.log",
            error_file: "logs/stat-sma002-out.log",
        },
        {
            name: "stat_sma003",
            script: "stat.js",
            args: "--account sma003",
            out_file: "logs/stat-sma003-out.log",
            error_file: "logs/stat-sma003-out.log",
        },
        {
            name: "stat_dcs012",
            script: "stat.js",
            args: "--account dcs012",
            out_file: "logs/stat-dcs012-out.log",
            error_file: "logs/stat-dcs012-out.log",
        },
        {
            name: "stat_dcs014",
            script: "stat.js",
            args: "--account dcs014",
            out_file: "logs/stat-dcs014-out.log",
            error_file: "logs/stat-dcs014-out.log",
        },
        {
            name: "stat_dcs015",
            script: "stat.js",
            args: "--account dcs015",
            out_file: "logs/stat-dcs015-out.log",
            error_file: "logs/stat-dcs015-out.log",
        },
    ],
};
