module.exports = {
    apps: [
        {
            name: "hedge",
            script: "hedge.js",
            args: "",
            out_file: "logs/hedge-out.log",
            error_file: "logs/hedge-error.log",
        },
        {
            name: "stat_dcs004",
            script: "stat.js",
            args: "--account dcs004",
            out_file: "logs/stat-dcs004-out.log",
            error_file: "logs/stat-dcs004-out.log",
        },
        {
            name: "stat_dcs005",
            script: "stat.js",
            args: "--account dcs005",
            out_file: "logs/stat-dcs005-out.log",
            error_file: "logs/stat-dcs005-out.log",
        },
        {
            name: "stat_dcs008",
            script: "stat.js",
            args: "--account dcs008",
            out_file: "logs/stat-dcs008-out.log",
            error_file: "logs/stat-dcs008-out.log",
        },
        {
            name: "stat_dcs009",
            script: "stat.js",
            args: "--account dcs009",
            out_file: "logs/stat-dcs009-out.log",
            error_file: "logs/stat-dcs009-out.log",
        },
        {
            name: "stat_dcs010",
            script: "stat.js",
            args: "--account dcs010",
            out_file: "logs/stat-dcs010-out.log",
            error_file: "logs/stat-dcs010-out.log",
        },
        {
            name: "stat_dcs011",
            script: "stat.js",
            args: "--account dcs011",
            out_file: "logs/stat-dcs011-out.log",
            error_file: "logs/stat-dcs011-out.log",
        },
        {
            name: "stat_sma001",
            script: "stat.js",
            args: "--account sma001",
            out_file: "logs/stat-sma001-out.log",
            error_file: "logs/stat-sma001-out.log",
        },
        {
            name: "stat_sma002",
            script: "stat.js",
            args: "--account sma002",
            out_file: "logs/stat-sma002-out.log",
            error_file: "logs/stat-sma002-out.log",
        },
        {
            name: "stat_sma003",
            script: "stat.js",
            args: "--account sma003",
            out_file: "logs/stat-sma003-out.log",
            error_file: "logs/stat-sma003-out.log",
        },
        {
            name: "stat_dcs012",
            script: "stat.js",
            args: "--account dcs012",
            out_file: "logs/stat-dcs012-out.log",
            error_file: "logs/stat-dcs012-out.log",
        },
        {
            name: "stat_dcs013",
            script: "stat.js",
            args: "--account dcs013",
            out_file: "logs/stat-dcs013-out.log",
            error_file: "logs/stat-dcs013-out.log",
        },
        {
            name: "stat_dcs014",
            script: "stat.js",
            args: "--account dcs014",
            out_file: "logs/stat-dcs014-out.log",
            error_file: "logs/stat-dcs014-out.log",
        },
        {
            name: "stat_dcs015",
            script: "stat.js",
            args: "--account dcs015",
            out_file: "logs/stat-dcs015-out.log",
            error_file: "logs/stat-dcs015-out.log",
        },
        {
            name: "stat_sma009",
            script: "stat.js",
            args: "--account sma009",
            out_file: "logs/stat-sma009-out.log",
            error_file: "logs/stat-sma009-out.log",
        },
        {
            name: "stat_sma010",
            script: "stat.js",
            args: "--account sma010",
            out_file: "logs/stat-sma010-out.log",
            error_file: "logs/stat-sma010-out.log",
        },
        {
            name: "stat_sma011",
            script: "stat.js",
            args: "--account sma011",
            out_file: "logs/stat-sma011-out.log",
            error_file: "logs/stat-sma011-out.log",
        },
        {
            name: "stat_sma012",
            script: "stat.js",
            args: "--account sma012",
            out_file: "logs/stat-sma012-out.log",
            error_file: "logs/stat-sma012-out.log",
        },
        {
            name: "stat_sma013",
            script: "stat.js",
            args: "--account sma013",
            out_file: "logs/stat-sma013-out.log",
            error_file: "logs/stat-sma013-out.log",
        },
    ],
};
